server:
  port: 8080
  servelet:
    context-path: /bootcamp
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jpostgres://pafzjljnrfdrpl:70170b3c6e2e71d5ced88a74b6f357274bf6125d809bec6eba5c49d1ab6e26de@ec2-34-230-115-172.compute-1.amazonaws.com:5432/db58rbb6rqkg7v

    username: pafzjljnrfdrpl
    password: 70170b3c6e2e71d5ced88a74b6f357274bf6125d809bec6eba5c49d1ab6e26de

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      
application:
  description: Projeto criado para o bootcamp DIO - Santander
